export const projects = [
  {
    id: 7,
    name: 'Privasea AI',
    description: 'Motion Design, Social Media Creative',
    live: 'https://x.com/Privasea_ai/status/1876962706894536876',
    tag: 'Next, Tailwind, Typescript, Next auth, Redis, postgresql, Shadcn',
    image: 'privasea.gif',
    createdOn: '2024',
    additionalTags: ['AI', 'SaaS'],
  },
  {
    id: 6,
    name: 'U1Core',
    description: 'Strategy, Motion Design, Website',
    live: 'https://www.u1core.com/',
    tag: 'Next, Tailwind, Typescript',
    image: 'u1core.gif',
    createdOn: '2024',
    additionalTags: ['New'],
  },
  {
    id: 5,
    name: 'DizArm',
    description: 'Strategy, Motion Design, Social Media',
    live: 'https://youtu.be/wdVjmtLbLDQ?si=gjkgF-XivOF5DDfl',
    tag: 'Next, Tailwind, Typescript, Next auth, Contentlayer, MDX',
    image: 'dizarm.gif',
    createdOn: '2023',
    additionalTags: ['New'],
  },
  {
    id: 1,
    name: 'Tik-Tok Affiliate',
    description: 'Strategy, Motion Design, Advertisement',
    live: 'https://youtu.be/YSB5wYS1iyc?si=yuy0s0qZpV5rK8Ey',
    tag: 'Next, Tailwind, Node, MongoDB, Express',
    image: 'tiktok.gif',
    createdOn: '2023',
  },
  {
    id: 3,
    name: 'Face Art',
    description: 'Motion Design, Showreel',
    live: 'https://www.behance.net/gallery/214636723/FACE-ART-BEAUTY-APP-MOBILE-APP-DESIGN',
    tag: 'React',
    image: 'faceart.webp',
    createdOn: '2019',
  },
  {
    id: 4,
    name: 'ClipSwift',
    description: 'Motion Design, Social Media',
    live: 'https://www.youtube.com/watch?v=XXrcPKM1t5E',
    tag: 'Node, CLI',
    image: 'clipswift.webp',
    createdOn: '2020',
  },
  // {
  //   id: 2,
  //   name: "E-commerce",
  //   description:
  //     "E-commerce website for selling t-shirt complete with payment options, with a simple UI.",
  //   github: "https://github.com/nishchay17/TeeStoreFrontend",
  //   live: "https://theteestore.netlify.app/",
  //   tag: "React, Node, MongoDB, Express",
  //   image: "tee.png",
  //   createdOn: "2019",
  //   additionalTags: ["No longer supported"],
  // },
];
