name: next js build workflow
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
          with:
            node-version: 14
      - name: Install node modules
        run: yarn
      - name: Build the project
        run: yarn build
      - name: Finish
        run: echo "run completed"

